TaxMax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# Este es el "directorio" de las rutas generales!!!
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TaxMaxapp.urls')),
    path('api/', include('TaxMaxapp.urls')),
    path('Nosotros/', include('TaxMaxapp.urls')),
    path('Servicio/', include('TaxMaxapp.urls')),    
    path('Registro/', include('TaxMaxapp.urls')),
    path('Login/', include('TaxMaxapp.urls')),
    path('Logout/', include('TaxMaxapp.urls')),
    path('Contacto/', include('TaxMaxapp.urls')),
    path('Main/', include('TaxMaxapp.urls')),
    path('listar_clientes',include('TaxMaxapp.urls')),
    path('editar_cliente/<str:rut>', include('TaxMaxapp.urls')),
    path('borrar_cliente/<str:rut>', include('TaxMaxapp.urls')),
    path('listar_clientes_full',include('TaxMaxapp.urls')),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TaxMaxapp/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *
app_name = 'gestion'

#---------- rutas de la API ----------------------------



urlpatterns = [    
    path('api/', views.API_objects.as_view()),
    path('api/<int:pk>/', views.API_objects_details.as_view()),
    path('', views.Main, name='Main'),
    path('Nosotros/', views.Nosotros, name='Nosotros'),
    path('Main/', views.Main, name='Main'),
    path('Servicio/', views.Servicio, name='Servicio'),
    path('Registro/', views.Registrar, name='Registro'),
    path('Login/', views.Usuario_login, name='Login'),
    path('Logout/', views.Usuario_logout, name='Logout'),
    path('Contacto/', views.Contacto, name='Contacto'),
    path('listar_clientes/',views.listar_clientes, name='listar_clientes'),
    path('editar_cliente/', views.editar_cliente, name='editar_cliente'),
    path('editar_cliente/<str:rut>', views.editar_cliente, name='editar_cliente'),
    path('borrar_cliente/', views.borrar_cliente, name='borrar_cliente'),
    path('borrar_cliente/<str:rut>', views.borrar_cliente, name='borrar_cliente'),
    path('listar_clientes_full',views.listar_clientes_full, name='listar_clientes_full'),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns)

TaxMaxapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext as _





class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rut = models.CharField('Rut', max_length=12, null=True)
    nombre = models.CharField('Nombre', max_length=50, null=True)
    email = models.EmailField('Email', max_length=50, null=True)
    fecha_nacimiento = models.DateField('Fecha Nacimiento', auto_now_add=True)
    telefono_contacto = models.CharField('Telefono', max_length=50, null=True)
    region = models.CharField('Region', max_length=50, null=True)
    comuna = models.CharField('Comuna', max_length=50, null=True)

    class Meta:
        permissions = (
            ('admin',('Es administrador')),
            ('cliente',_('Es cliente')),
        )

    def __str__(self):
        return self.rut
        


class Servicio(models.Model):
    id_cliente = models.ForeignKey(Cliente, null=True, on_delete=models.CASCADE)
    Tipo_servicio = (
        ('Plan Estandar', 'Plan Estandar'),
        ('Plan Premium', 'Plan Premium'),
        ('Tax Master', 'TaxMaster'),
    )
    precio = models.IntegerField('costo', null=True)
    tipo = models.CharField('tipo', null=True, max_length=20, choices=Tipo_servicio)

    def __str__(self):
        return self.tipo

TaxMaxapp/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Cliente, Servicio
from django import forms


class PerfilUsuarioForm(forms.ModelForm):
    class Meta():
        model = Cliente
        fields=[
            'rut', 
            'nombre',                  
            'telefono_contacto',
            'region',
            'comuna'
        ]

        labels={            
            'rut':'Rut valido',    
            'nombre':'Nombre Completo',     
            'telefono_contacto':'Celular',
            'region':'Region',
            'comuna':'Comuna'
        }  


class RegistroForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields=[
            'username',
            'email',
            'password'
            
        ]
        labels={
            'username':'Nombre de usuario',
            'email':'Correo',
            'password':'Contraseña'
            

        }
        help_texts={
            'username':'Usuario AQUI!!',
            'email':'Ingrese correo AQUI!!',
            'password':'Contraseña AQUI!!'
            
        }
        error_messages ={
            'username':{
                'max_length':'Maximo 20 caracteres',
                'min_length':'Minimo 8 caracteres',
                'required':'Requerido'
            },
            'email':{
                'required':'Requerido'
            },
            'password':{
                'min_length':'Minimo 8 caracteres',
                'required':'Requerido'
            }
            

        }

    def __init__(self, *args, **kwargs):
        super(RegistroForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'forms-control'})
        self.fields['email'].widget.attrs.update({'class': 'forms-control'})
        self.fields['password'].widget.attrs.update({'class': 'forms-control'})
        

TaxMaxapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django import forms
from .models import Cliente,Servicio
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import RegistroForm, PerfilUsuarioForm
from .serializers import ClienteSerializer
from rest_framework import generics


class API_objects(generics.ListCreateAPIView):
        queryset = Cliente.objects.all()
        serializer_class = ClienteSerializer

class API_objects_details(generics.RetrieveUpdateDestroyAPIView):
        queryset = Cliente.objects.all()
        serializer_class = ClienteSerializer

def listar_clientes(request):
    clientes = Cliente.objects.all()
    return render(request,
        "gestion/listar_clientes.html" , {'clientes' : clientes})

def listar_clientes_full(request):
    clientes = Cliente.objects.all()
    return render(request,
        "gestion/listar_clientes_full.html", {'clientes' : clientes})


def editar_cliente(request, rut):
    instancia= Cliente.objects.get(rut=rut)
    form= PerfilUsuarioForm(instance=instancia)
    if request.method=="POST":
        form= PerfilUsuarioForm(request.POST, instance=instancia)
        if form.is_valid():
            instancia= form.save(commit=False)
            instancia.save()
    return render(request, "gestion/editar_cliente.html",{'form':form})

def borrar_cliente(request, rut):
    instancia= Cliente.objects.get(rut=rut)
    instancia.delete()
    return redirect('gestion:listar_clientes_full')


def Servicio(request):

    return render(request,'gestion/Servicio.html') 

def Main(request):

    return render(request, 'gestion/Main.html')

def Nosotros(request):

    return render(request,'gestion/Nosotros.html')    

def Contacto(request):

    return render(request,'gestion/Contacto.html')      
    
def Usuario_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('gestion:Main'))

def Index(request):
    return render(request, 'gestion/Main.html')    


def Usuario_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('gestion:Main'))
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    if request.user.is_superuser:
                        login(request, user)
                        return HttpResponseRedirect(reverse('gestion:admin.html'))
                    else:    
                        login(request, user)
                        return HttpResponseRedirect(reverse('gestion:Main'))
                else:
                    return HttpResponse("Tu cuenta está inactiva    UwU")      
            else: 
                print("username: {} - password: {}".format(username, password))
                return HttpResponse("Datos Inválidos")
        else:
            return render(request, 'gestion/Login.html',{})        


def Registrar(request):
    registrado= False
    if request.method == 'POST':
        user_form = RegistroForm(data=request.POST)
        profile_form = PerfilUsuarioForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registrado = True
        else:       
            print(user_form.errors, profile_form.errors)     
            return HttpResponse("Datos Invalidos")    
    else:
        user_form = RegistroForm()     
        profile_form = PerfilUsuarioForm()

    return render(request, 'gestion/Registro.html',
                     {'user_form': user_form,
                     'profile_form': profile_form,
                     'registrado': registrado})


def post_list(request):
    user = request.user
    if user.has_perm('TaxMaxapp.cliente'):
        posts = Post.objects.filter(
            published_date__lte=timezone.now()).order_by('published_date')
        return render(request, 'gestion/post_list.html', {'posts': posts})
    else:
        return render(request, 'gestion/main.html')  

# ---importamos nuestras estruras ---------------


# Create your views here.

TaxMaxapp/templates/gestion/Contacto.html
{% extends 'Base/base.html' %}
{% load staticfiles %}
{%block div%}
<form action="#" method="post" id="formulario1" novalidate="novalidate">
                            <table class="table table-hover">
                                <tr>
                                    <td> <label for="txtNombre">Nombre</label> </td>
                                    <td> <input type="text" name="txtNombre" 
                                   id="txtNombre" placeholder="Ingrese nombre" onkeypress="return validaLetras(event)" ></td>
                                </tr>
                                <tr>
                                        <td> <label for="rut">Rut</label> </td>
                                        <td> <input type="text" id="rut" name="rut" onkeypress="return isNumber(event)" 
                                        placeholder="Ingrese RUT" > 
                                       </td>
                                    </tr>
                                <tr>
                                    <td> <label for="txtEmail">Email</label> </td>
                                    <td> <input type="email" name="txtEmail" 
                                        id="txtEmail" placeholder="Ingrese Correo"  > </td>
                                </tr>
                                
                                <tr>
                                        <td><label for="start">Fecha de Nacimiento</label></td>
                                        <td>  <input type="date" id="start" name="start" max="2001-12-31">
                                             </td>
                                </tr>
                                <tr> 
                                        <td> <label for="txtTelefono">Telefono De contacto</label> </td>
                                        <td> <input type="text" name="txtTelefono" 
                                            id="txtTelefono" placeholder="ejemplo: 954325674" onkeypress="return isNumber(event)" >  </td>
                                </tr>
                                <tr> 
                                        <td> <label for="regiones">Regiones</label> </td>
                                    <td><select id="regiones"><option value="sin-region">
                                    Seleccione región</option>
                                </select> </td>
                                </tr> 
                                <tr> 
                                        <td> <label for="comunas">Comuna</label> </td>
                                        <td><select id="comunas">
                                        <option value="sin-comuna" >Seleccione comuna</option>
                                         </select>
                                        </td>
                                </tr>

                                <tr> 
                                        <td> <label for="txtServicio">Tipo de Servicio</label> </td>
                                        <td><select id="txtServicio">
                                        <option value="sin-servicio">Seleccione Servicio</option>
                                         <option value="sin-Servicio">--</option>
                                         <option value="Estandar">Estandar</option>
                                         <option value="Premium">Premium</option>
                                         <option value="TaxMaster">TaxMaster</option>
                                        </select>
                                         </td>
                                        
                                </tr>
                               
                                
                                
                            </table>
                            <br>
                            <button type="submit">Enviar</button>
                        </form>


{%endblock div%}

TaxMaxapp/templates/gestion/Login.html
{% extends 'Base/base.html' %}
{% load staticfiles %}

{% block div %}
<div  class="login">
    <h1>INICIAR SESIÓN</h1>
<form  method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" name="username" placeholder="Nombre de Usuario">
    </div>

    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" name="password" placeholder="Contraseña OwO">


    </div>
    

<button type="submit" class="btn btn-primary">Iniciar Sesión</button>

</form>
</div>


{% endblock div%}

TaxMaxapp/templates/gestion/Main.html
{% extends 'Base/base.html' %}
{% load staticfiles %}

{% block title %}
Principal
{% endblock title %}
{% block div %}
{% if user.is_superuser %}
<h1>--BIENVENIDO ADMINISTRADOR--</h1>
{% else %}
<div style=" height: 100%" class="col-md-7">
                <h2 class="featurette-heading">Tax Max.</h2>
                <br>
                <p class="lead">Tax Max SpA, 
                    es una empresa conformada por un equipo de profesionales que 
                    ofrecemos servicios Contables, Tributarios, Laborales, Financieros, 
                    Auditorias y todo el asesoramiento necesario para su empresa o negocio, 
                    al mejor precio y con una alta calidad. Nuestra misión es brindar un servicio 
                    profesional de alta calidad para la toma de decisiones, a un precio adecuado 
                    para sus necesidades, con el fin de que cualquier empresa, pueda disponer del 
                    apoyo necesario para optimizar su negocio. Asesoramos sus proyectos de inversión, 
                    prestamos bancarios y demás. El asesoramiento será constante y de ser necesario 
                    vía on-line, para que no tenga que desplazarse y pueda hacer todas las gestiones y consultas desde su empresa.</p>
            </div>
            <div id="img">
                <img  id="imgTamaño" src="{% static 'img/nuestro_1.png'%}" alt="nuestro_1" >
                <!-- class="col-md-5" -->
                <!-- class="featurette-image img-responsive" -->
                <!-- alt="Generic placeholder image" -->
            </div>
             
        </div>
            
        

        <div style="padding:100px;"  class="row featurette">
         <hr class="featurette-divider">
         <br>
        
            <div class="col-md-5"> 
                <img id="imgTamaño" src="{% static 'img/nuestro_2.jpg'%}" alt="imgane">
            </div>
            <div class="col-md-7">
                <h2 class="featurette-heading">Nuestro Pensar</h2>
                <br>
                <div  class="lead" style="background-color:white;  white-space: normal;">
                    <p>Nos enorgullecemos de comprender los problemas y 
                    oportunidades de la consultoría. Nuestra empresa está 
                            comprometida a lograr la excelencia y esto es notorio en todos
                             nuestros servicios. Nuestros clientes son nuestra mejor posesión y
                              estamos dedicados a servir sus necesidades.</p>
                    
                    
                </div>
            </div>
{% endif %}

{% endblock div %}

TaxMaxapp/templates/gestion/Nosotros.html
{% extends 'Base/base.html' %}
{% load staticfiles %}

{% block div %}
<div class="container marketing">

       

        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">Nuestro Estudio.</h2>
                <br>
                <p class="lead"> 
                    En Tax Max SpA, nos especializamos en brindar asesorías 
                    contables, financieras, tributarias, laborales, legales y comerciales a 
                    pequeñas y medianas empresas.Somos un Estudio que cuenta con 
                    profesionales capacitados, los cuales cuentan con un sistema de 
                    actualizaciones continuas y un equipo de análisis de las normas vigentes,
                    ofreciéndoles un servicio competitivo y de calidad.Contamos con experiencia asesorando empresas de variados rubros.</p>
            </div>
            <div id="img" >
                <img id="imgTamaño" src=" {% static 'img/4-min.png'%}" alt="nuestro_1" >
                <!-- class="col-md-5" -->
                <!-- class="featurette-image img-responsive" -->
                <!-- alt="Generic placeholder image" -->
            </div>
        </div>

       

        <div class="row featurette">
         <hr class="featurette-divider">
            <div class="col-md-5">
                <img class="featurette-image img-responsive" id="img2" src="{% static 'img/imagen_2-min.jpg'%}" alt="imgane">
            </div>
            <div class="col-md-7">
                <h2 class="featurette-heading">Nuestra Vision</h2>
                <br>
                <div class="lead" style="background-color:white;  white-space: normal;">
                    <p>Ser reconocidos como uno de los principales estudios de 
                        asesoría especializada en pequeñas y medianas empresas en pleno 
                        crecimiento en nuestro país, contribuyendo a formalizar e incrementar
                         la participación en el mercado..</p>
                    
                    
                </div>
            </div>
        </div>

        

{% endblock div %}

TaxMaxapp/templates/gestion/Registro.html
{% extends 'Base/base.html' %} 
{% load staticfiles %}

{% block div %}

<div class="jumbotron">
    {% if registrado %}
    <h1>--GRACIAS POR REGISTRARTE-- SERAS HACKIADO</h1>
    {% else %}
    <h1>Registro</h1>
    <h3>Llena los siguientes datos:</h3>
    <form enctype="multipart/form-data" method="POST">
    {% csrf_token%}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit" class="btn btn-primary"> Registrar</button>
    </form> 


    {% endif%}
</div>


{% endblock div %}

TaxMaxapp/templates/gestion/Servicio.html
{% extends 'Base/base.html' %} {% block div %}


<div class="container marketing">
  <hr class="featurette-divider" />

  <div id="servicio" class="row featurette">
    <div>
      <h2 class="featurette-heading">Nuestros Servicios</h2>
      <br />
      <div id="Contable" class="col-md-5">
        <h3 id="tex">
          Asesoría Contable: <br />
          <br />
          °Teneduría de libros <br />
          °Informes financieros y reportes a <br />
          solicitud de la empresa para toma de decisiones. <br />
          °Presentación y exposición de los <br />
          estados financieros y de resultados. <br />
          °Evaluación de la situación económica y <br />
          financiera de la empresa a través de indicadores financieros. <br />
          °Asesoría en inversiones y créditos financieros, así como <br />
          la preparación de expedientes para su obtención. <br />
        </h3>
      </div>

      <div id="Financiera" class="col-md-5">
        <h3 id="tex1">
          Asesoría Financiera: <br />
          <br />
          °Confección de Estados Financieros: <br />
          Balance General, Estado de Resultados, <br />
          Estado de flujo de efecivo, Flujo de Caja y <br />
          Notas de interpretación Financiera. <br />
          °Les proporcionamos orientación y posibles <br />
          alternativas para estar mejor preparados <br />
          ante cualquier cambio en el mercado. <br />
        </h3>
      </div>
    </div>
  </div>

  <hr class="featurette-divider" />

  <div style="width: 100%; height: auto; display: flex;">
    <div style="width: 30%; height: 350px;" id="estandar">
      <h2 class="featurette-heading">Plan Estándar</h2>


      <div style="height: 100%; width: 100%; padding: 10px;">
        <div
          class="lead"
          style="background-color:lightgray;  white-space: normal; width: 100%; height: auto;"
        >
          <p>
            Este plan ofrece los servicios básicos a la hora de asesorarte en
            tus problemas de Contabilidad
          </p>
        </div>
<br>
<br>
<br>
        <button
          id="butonest"
          class="btn btn-primary"
          onclick="window.location.href={% url 'gestion:Contacto' %}"
        >
          Seleccionar Plan
        </button>
        <br />
      </div>
    </div>
    <!-- biennnnnnnnnnnn -->

    <div style="width: 30%; height: 350px;"  id="premium">
      <h2 class="featurette-heading">Plan Premuim</h2>
      <br />

      <div style="height: 100%; width: 100%; padding: 10px;">
        <div
          class="lead"
          style="background-color:rgb(81, 121, 173);   white-space: normal; width: 100%;"
        >
          <p>
            Este plan te ofrece los servicios básicos además de otras prestaciones que llevaran tu experiencia a un nivel mucho mas alto


          </p>
        </div>

        <button
          id="butonest"
          class="btn btn-primary"
          onclick="window.location.href={% url 'gestion:Contacto' %}"
        >
          Seleccionar Plan
        </button>
  
        <br />
      </div>
    </div>

    <!-- asdasdasdasdgggggggggggggggggggggggggggggggggggggggggggggggggggg -->

    <div style="width: 30%; height: 100%"  id="taxmas">
      <h2 class="featurette-heading">Tax Master</h2>
     

      <div style="height: 100%; width: 100%; padding: 10px;">
        <div
          class="lead"
          style="background-color:orange;  white-space: normal; width: 100%; height: 197px;"
        >
          <p>
            Este plan ofrece los servicios de los demas planes además de
            asistencia personalizada 24/7 y un curso de financiamiento para así
            obtener una experiencia Tax Max única.
          </p>
        </div>

        <button
          id="butonest"
          class="btn btn-primary"
          onclick="window.location.href={% url 'gestion:Contacto' %}'"
        >
          Seleccionar Plan
        </button>
        <br />
      </div>
    </div>
  </div>
</div>

{% endblock div %}

TaxMaxapp/templates/gestion/borrar_cliente.html
{% extends 'Base/base.html' %}

TaxMaxapp/templates/gestion/editar_cliente.html
{% extends 'Base/base.html' %}
{% block div %}

Editar Cliente



<form method="POST">
    {% csrf_token %}
    {{form}}
<button type="submit">Grabar</button>        
</form>


{% endblock div %}

TaxMaxapp/templates/gestion/listar_clientes.html
{% extends 'Base/base.html' %}
{% load staticfiles %}

{% block div %}
 <table class="table">
        <thead class="thead-dark">
           <tr>
                
                <th>RUT</th>
                <th>NOMBRE</th>
                <th>EMAIL</th>
                <th>FECHA NACIMIENTO</th>
                <th>TELEFONO</th>
                <th>REGION</th>
                <th>COMUNA</th>
                <th>USER</th>
            </tr>
        </thead>
        <tbody>
           {% for c in clientes %}
            <tr>
                <td>{{c.rut}}</td>
                <td>{{ c.nombre}}</td>
                <td>{{c.email}}</td>
                <td>{{c.fecha_nacimiento}}</td>
                <td>{{c.telefono}}</td>
                <td>{{c.region}}</td>  
                <td>{{c.comuna}}</td>
                <td>{{c.user}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


{% endblock div %}

TaxMaxapp/templates/gestion/listar_clientes_full.html
{% extends 'Base/base.html' %}

{% block div %}
<table class="table">
        <thead class="thead-dark">
            <tr>
                
                <th>RUT</th>
                <th>NOMBRE</th>
                <th>EMAIL</th>
                <th>FECHA NACIMIENTO</th>
                <th>TELEFONO</th>
                <th>REGION</th>
                <th>COMUNA</th>
                <th>USER</th>
            </tr>
        </thead>
        <tbody>
            {% for c in clientes %}
            <tr>
                <td>{{c.rut}}</td>
                <td>{{ c.nombre}}</td>
                <td>{{c.email}}</td>
                <td>{{c.fecha_nacimiento}}</td>
                <td>{{c.telefono}}</td>
                <td>{{c.region}}</td>  
                <td>{{c.comuna}}</td>
                <td>{{c.user}}</td>
                <td><button class="btn btn-warning"><a href="/editar_cliente/{{ c.rut }}" >EDITAR</a></button></td>
                <td><button  onclick="return confirm('Se eliminara un cliente Seguro que desea continuar?')" class="btn btn-danger " class="alert alert-danger" role="alert"><a href="borrar_cliente/{{ c.rut }}" >Eliminar</a></button> </td>
                
                
            </tr>
            {% endfor %}
        </tbody>
       
    </table>
   
{% endblock div %}